export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
import Link from "next/link";
import styles from "./page.module.css";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className={styles.global_header}>HEADER</div>
        <div className={styles.nav_bar}>
          <Link href="/chatting">채팅</Link>
          <Link href="/friends">친구 목록</Link>
        </div>
        {children}
      </body>
    </html>
  );
}
